---
title: "Tutorial Quiz Questions in `learnr`"
output:
  learnr::tutorial:
runtime: shiny_prerendered
resource_files:
- .secrets/9566fe0643cfe888fecd0b72f870afec_cansav09@gmail.com
- .secrets/986a84aaed0662458cd8a3e0959a8fc7_cansav09@gmail.com
tutorial:
  # id: "com.example.tutorials.my-first-tutorial"
  version: 2.18
  # user_id: "barret"
description: >
  This is a test for DataTrail
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = TRUE, highlight = TRUE)
tutorial_options(exercise.eval = FALSE)
```

```{r global, include=FALSE}
#### Code for authenticating to a googlesheet to write grades to
library(DT)
library(gsheet)
library(magrittr)
library(shiny)
library(googlesheets4)
library(googledrive)
```

```{r set-sheet, include=FALSE}
sheet_url <- "https://docs.google.com/spreadsheets/d/1MSlsIJUegsDySU7EOK4gBvK5XjTNkyLArrHC7-jOXfs/edit#gid=0"

sheet_id <- "Sheet1"
```

```{r, include=FALSE}
authenticate <- function() {
  # designate project-specific cache
  options(gargle_oauth_cache = ".secrets")

  # check the value of the option, if you like
  gargle::gargle_oauth_cache()

  if (interactive()) {
    googledrive::drive_deauth()
    googledrive::drive_auth(
      email = "cansav09@gmail.com",
      path = NULL,
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      # Get new token if it doesn't exist
      cache = ".secrets/",
      use_oob = FALSE,
      token = NULL
    )
  } else {
    googledrive::drive_deauth()
    googledrive::drive_auth(
      email = "cansav09@gmail.com",
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      cache = ".secrets/"
    )
  }
}

recorder <- function(tutorial_id, tutorial_version, user_id, event, data){
  timestamp = Sys.time()

  data$tutorial_id = tutorial_id
  data$tutorial_version = tutorial_version
  data$user_id = user_id
  data$timestamp = timestamp

  recorded_answers <- data.frame()
  # https://rstudio.github.io/learnr/articles/publishing.html#recording-events
  
  if (event == "question_submission" & data$label == "email") {
    
    recorded_answers <- data.frame(email = data$answer)
    # Write email to googlesheet
    
    authenticate()
  }
  # Only write things down if its a question submission
  if (event == "question_submission" & !(data$label == "email")) {
    
    # This needs to be fixed 
    colnames(recorded_answers) <- c("email", colnames(recorded_answers), data$label)
  
    recorded_answers["email", data$label] <- data$answer
  
    readr::write_tsv(recorded_answers, "recorded_answer.tsv")
  
    googlesheets4::sheet_write(
        data = recorded_answers,
        ss = googledrive::drive_get(id = sheet_url)$id,
        sheet = "Sheet1"
      )
  }
}
options(tutorial.event_recorder = recorder)
```

Ask the student to give their email. If it is in our database, we will record it. But we can send them their final grade regardless.

```{r email, echo=FALSE}
question_text(
  "Enter your email",
  answer_fn(function(value) {
    if (grepl("^[[:alnum:].-_]+@[[:alnum:].-]+$", value)) {
      correct(messages = "Thanks for giving your email. Now your grade will be logged")
    } else {
      incorrect(messages = "This doesn't look like an email")
    }
  })
)
```

Can include multiple choice questions like so:

```{r letter-a, echo=FALSE}
question(
  "What number is the letter A in the English alphabet?",
  answer("8"),
  answer("14"),
  answer("1", correct = TRUE),
  answer("23")
)
```


Include some text here about how to go complete a swirl module

```{r swirl-code, echo=FALSE}
question_text("Enter your swirl code.",
  answer_fn(function(value) {
    if (grepl(".+(HEri|Gu8m|sm8p|sRVV|s7ST|k0it|gZLu|bRkJ|xouE|23nK).+", value)) {
      correct(messages = "Great job completing the swirl module!")
    } else {
      incorrect(messages = "Did you get this code from this chapter's swirl module?")
    }
  }
)
)
```



```{r}
## Look for recognized emails in a given database and record all the quiz answers in the row of that email 
  ### Code to write answers to googlesheet after an email is supplied
```


```{r}
## Calculate a total score/grade for this quiz submission

```


```{r}
### Code to report the user's overall grade for this quiz to the user

```
